<?php view::content() ?>
<?= Form::open() ?>
    <?php if(!$esAdministradorUsuarios): ?>
        <?= Form::label('Password actual', 'pass') ?>
        <?= Form::password('pass') ?>
    <?php endif ?>
    <?= Form::label('Nuevo Password', 'pass1') ?>
    <?= Form::password('pass1') ?>
    <?= Form::label('Confirmar password', 'pass2') ?>
    <?= Form::password('pass2') ?>
    <?= Form::submit('Actualizar') ?>
    <?= Html::link((new Perfil)->getViewInicial(), 'Inicio') ?>
<?= Form::close() ?>