<div>
<?php View::content()?>
<h1><?= ucwords("$model"), ": <span>$action_name</span>" ?></h1>
<div class="actions">
    <?= Html::linkAction("crear/", 'Crear registro', 'class="btn btn-primary"')?>
</div>
<?php if (isset($data->items) && (count($data->items) > 0)) : ?>
<table class="t">
    <thead><tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Login</th>
        <th>Perfil</th>
        <th>Acciones</th>        
    </tr></thead>
	<tbody>
    <?php foreach ($data->items as $item) : ?>
        <tr>            
            <td><?= h($item->id) ?></td>
            <td><?= h($item->nombre) ?></td>
            <td><?= h($item->apellido) ?></td>
            <td><?= h($item->login) ?></td>
            <td><?= h($item->getPerfil()->nombre ) ?></td>
			<td><?= Html::linkAction("ver/$item->id", 'Ver')?> |
			<?= Html::linkAction("editar/$item->id", 'Editar')?> |
            <?= Html::linkAction("cambiar_password/$item->id", 'Cambiar pass')?> |
			<?= Html::linkAction("borrar/$item->id", 'Borrar', 'onclick="return confirm(\'¿Está seguro?\')"') ?>
			</td>
        </tr>
    <?php endforeach?>
	</tbody>
</table>
<?php View::partial('paginators/digg', false, array('page' => $data ,'url' => Router::get('controller_path').'/index')) ?>

<?php else : // Si no hay items?>
<h2>No hay ningún registro</h2>
<?php endif ?>
</div>
